aspell             =  true
at                 =  true
autoconf           =  true
automake           =  true
avahi              =  true
bashInteractive    =  true
bash               =  true
bc                 =  true
bind               =  true
binutils           =  true
bsdiff             =  true
bzip2              =  true
cmake              =  true
coreutils          =  true
cpio               =  true
cron               =  true
cups               =  true
dbus               =  true
dhcp               =  true
diffutils          =  true
e2fsprogs          =  true
emacs              =  true
enscript           =  true
file               =  true
findutils          =  true
flex               =  true
gcc                =  true
gcj                =  true
glibcLocales       =  true
glibc              =  true
gnugrep            =  true
gnum4              =  true
gnumake            =  true
gnupatch           =  true
gnupg              =  true
gnuplot            =  true
gnused             =  true
gnutar             =  true
gnutls             =  true
grub2              =  true
grub               =  true
gsl                =  true
guile              =  true
gzip               =  true
hddtemp            =  true
hdparm             =  true
hello              =  true
host               =  true
iana-etc           =  true
icewm              =  true
idutils            =  true
inetutils          =  true
iputils            =  true
jnettop            =  true
jwhois             =  true
kbd                =  true
kvm                =  true
lapack-reference   =  true
less               =  true
lftp               =  true
libtool_2          =  true
libtool            =  true
libxml2            =  true
libxslt            =  true
lout               =  true
lsh                =  true
lsof               =  true
ltrace             =  true
lvm2               =  true
lynx               =  true
man-pages          =  true
man                =  true
mcabber            =  true
mcron              =  true
mc                 =  true
mdadm              =  true
midori             =  true
mingetty           =  true
mktemp             =  true
mk                 =  true
monotone           =  true
mono               =  true
mpg321             =  true
mutt               =  true
mysql              =  true
netcat             =  true
nfs-utils          =  true
nix                =  true
nixUnstable        =  true
nss_ldap           =  true
nssmdns            =  true
ntfs3g             =  true
ntp                =  true
openssh            =  true
openssl            =  true
pan                =  true
par2cmdline        =  true
pciutils           =  true
pdf2xml            =  true
perl               =  true
pkg-config         =  true
pmccabe            =  true
procps             =  true
python             =  true
qemu_kvm           =  true
qemu               =  true
readline           =  true
rlwrap             =  true
rpcbind            =  true
rpm                =  true
rsync              =  true
screen             =  true
scrot              =  true
sdparm             =  true
sharutils          =  true
sloccount          =  true
smartmontools      =  true
sqlite             =  true
squid              =  true
ssmtp              =  true
stdenv             =  true
strace             =  true
sudo               =  true
su                 =  true
sysklogd           =  true
syslinux           =  true
sysvinit           =  true
sysvtools          =  true
tcl                =  true
tcpdump            =  true
texinfo            =  true
time               =  true
tinycc             =  true
udev               =  true
unzip              =  true
usbutils           =  true
util-linuxMinimal  =  true
util-linux         =  true
w3m                =  true
webkitgtk          =  true
wget               =  true
which              =  true
wirelesstools      =  true
wireshark          =  true
wpa_supplicant     =  true
xfsprogs           =  true
xkeyboard_config   =  true
xz                 =  true
zile               =  true
zip                =  true
